### ISSUE TITLE
Download GISAID metadata and/or sequence data via RSelenium?

### ISSUE THREAD

**Issue by tomwenseleers** [Wytamma/GISAIDR#26]
While I liked the features of this package, it is unfortunate that scraping many records in the way it is done now is very slow.
I wonder if it would not be possible to use RSelenium instead, and mimic what one would do if one were to do these searches and downloads by manually logging into the GISAID website, i.e. enter credentials, press login button, press search tab, enter your search terms (e.g. Oceania, with submission date since 2022-07-26), click checkbox at the top of the column to check all records that the search returned, press Download at the bottom, select desired download (e.g. patient metadata or FASTA), press download button & tsv file will be downloaded (as long as fewer than 10 000 records were selected, otherwise a message will pop up requesting fewer than 10 000 records to be selected per download batch). For this particular search (ca. 1000 records) this takes mere seconds, while using GISAIDR it now takes 7 minutes, ie >80x slower. I also see that in the returned dataframe key fields like Lineage and  AA Substitutions are missing, e.g.
```
df_oceania = query(credentials = credentials, location = "Oceania", 
                from_subm = "2022-07-26", 
                to_subm = "2022-07-28",
                load_all = TRUE)
names(df_oceania)
 [1] "id"                      "virus_name"             
 [3] "passage_details_history" "accession_id"           
 [5] "collection_date"         "submission_date"        
 [7] "information"             "length"                 
 [9] "host"                    "location"               
[11] "originating_lab"         "submitting_lab"
```

whereas a metadata tsv downloaded as above would contain the fields
```
 [1] "Virus name"                      "Accession ID"                   
 [3] "Collection date"                 "Location"                       
 [5] "Host"                            "Additional location information"
 [7] "Sampling strategy"               "Gender"                         
 [9] "Patient age"                     "Patient status"                 
[11] "Last vaccinated"                 "Passage"                        
[13] "Specimen"                        "Additional host information"    
[15] "Lineage"                         "Clade"                          
[17] "AA Substitutions"
```

Is that supposed to be like that?

In the answer here I show how to download the complete GISAID patient metadata download package using RSelenium:
[https://stackoverflow.com/questions/72632118/download-covid-patient-metadata-from-gisaid-website-in-r-using-rselenium](url)
This could be a nice feature to implement as well (alongside the ability to download the other provided download packages). Downloading that (12 million records) & reading it in on my computer just takes 2 mins vs ca 1400 hours (58 days) if one were to try to scrape it all using GISAIDR with the current implementation... 

PS What I wanted to use GISAIDR for is to combine the GISAID patient metadata download package (which I now download using RSelenium) with the metadata from the records submitted over the last 3 days (which are missing from the GISAID patient metadata download package). But I would definitely need the fields "Host", "Lineage" and "AA Substitutions" for my analyses...

**Comment by Wytamma** [comment]
Hey @tomwenseleers! Thanks for the write up! Yep basically when I first wrote GISAIDR you were able to query 10,000 results at a time by changing the `rows_per_page` URL query param in the request sent to GISAID. However, GISAID has now changed this (a few months ago) so you can only query a max of 50 at a time using the `rows_per_page` param. 

RSelenium seems like a valid solution, but I'm basically mimicking what it does by directly sending HTTP request instead of using a web driver e.g. we can add this select all feature without RSelenium. Weirdly I have a 5,000 record download limit on GISAID not 10,000. In any case, is it possible to select less than 10,000 results with select all check box? I.e. if the search matches >10,000 are able to download the sequences? 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/13726005/181865983-f7633ce2-5d05-4f81-83a2-febc56aac57b.png">

I'm not sure about the the difference in columns between the downloaded metadata and the `query` results... to get the full metadata i.e. the same action as clicking `download` you need to use the `GISAIDR::download` function not `query`. The results for `download` has `pangolin_lineage` and `host`, however, when I download a metadata file there is no AA Substitutions column... I'm not sure why we have different columns. It seems maybe are getting different results from GISAID? I'd be keen to go though this in more detail if you have time.

**Comment by Wytamma** [comment]
I added a `fast` option to `query` in [2b100fd](https://github.com/Wytamma/GISAIDR/commit/2b100fdfca9d4b8e468a6aa5aa1b21479d534b2b) see https://github.com/Wytamma/GISAIDR#fast-query.

This implements the `check-all` solution above. For example, the code below downloads all the matching entires in one go. 

```R
df <- query(
  credentials = credentials, 
  location = "Oceania", 
  from_subm = "2022-07-26", 
  to_subm = "2022-07-28",
  fast = TRUE
)
full_df <- download(credentials = credentials, list_of_accession_ids = df$accession_id)
```

This solution has the benefit of letting you download the matching entries in batches using `download` if there are > 5000 matches. 

I'm still not sure about the differences in metadata, but I'll create another issue for that specifically.
